[MM-8]: added topic for starting meeting
mattermost-community/mattermost-plugin-msteams-meetings pull request #109
Opened 2024-07-30 12:57 UTC by Kshitij-Katiyar

### Summary
Updated slash command to start a meeting to support adding topic to a meeting
#### Existing command: `/mstmeetings start`
#### Updated command: `/mstmeetings start DEMO_MEETING_TOPIC`

### Screenshot
![image](https://github.com/user-attachments/assets/f63225fe-1173-49e1-9472-449c4ba3e7c3)

2024-07-30 16:33 UTC, raghavaggarwal2308 requested changes

2024-07-30 16:33 UTC, raghavaggarwal2308 commented on server/command.go
We will have to change the meeting topic in the api call we are making for creating the meeting. In `meeting.go` file

2024-07-31 19:39 UTC, raghavaggarwal2308 approved these changes

2024-08-10 17:15 UTC, wiggin77 commented on server/meeting.go
> +		subject = "MS Teams Meeting"
```suggestion
		subject = "Microsoft Teams Meeting"
```

2024-08-10 17:18 UTC, wiggin77 approved these changes

2024-08-14 08:20 UTC, AayushChaudhary0001 commented
While testing this PR I have found 2 issues.

1. Multiple arguments allowed with spacing
2. No limit on length of the meeting topic

I am attaching screenshots supporting above statements, please take a look and see if we can fix them. Option 1 would be an enhancement(as MM considers each word as an argument), but option 2 should be fixed as it would be considered as a bug.

**For point 1:-**
![image](https://github.com/user-attachments/assets/25bcf735-add8-44fb-a45b-ff0f22e4c4d8)

**For point 2:-** 
![image](https://github.com/user-attachments/assets/4976d1e6-c2fe-41df-93f6-1a11f27ca60c)

2024-08-14 09:15 UTC, Kshitij-Katiyar commented
> While testing this PR I have found 2 issues.
> 
> 1. Multiple arguments allowed with spacing
> 2. No limit on length of the meeting topic
> 
> I am attaching screenshots supporting above statements, please take a look and see if we can fix them. Option 1 would be an enhancement(as MM considers each word as an argument), but option 2 should be fixed as it would be considered as a bug.
> 
> **For point 1:-** ![image](https://private-user-images.githubusercontent.com/116162036/357733129-25bcf735-add8-44fb-a45b-ff0f22e4c4d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjY5NTUsIm5iZiI6MTcyMzYyNjY1NSwicGF0aCI6Ii8xMTYxNjIwMzYvMzU3NzMzMTI5LTI1YmNmNzM1LWFkZDgtNDRmYi1hNDViLWZmMGYyMmU0YzRkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwOTEwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjdjNjJiN2ZkZjBmYWIyOWIyMzBhMjU5NTkzMTgxMjMzOWIwYWY0ODdlM2VmYzlkMzdkOGVkODYyNTYxOTM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FcMCTI5UnUKtezSnTqXf99N65tCRuMc-0chDj10H2qw)
> 
> **For point 2:-** ![image](https://private-user-images.githubusercontent.com/116162036/357733570-4976d1e6-c2fe-41df-93f6-1a11f27ca60c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjY5NTUsIm5iZiI6MTcyMzYyNjY1NSwicGF0aCI6Ii8xMTYxNjIwMzYvMzU3NzMzNTcwLTQ5NzZkMWU2LWMyZmUtNDFkZi05M2Y2LTFhMTFmMjdjYTYwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwOTEwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzUwODBmYmE5MWRlNWE5OTA3NzNmOWQxZTRkZTc3ODgwMjI0NGUwMDVjZmIzN2Q0YzVkZGY4MDEwYzQ4NmM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z4WiSqiCKj1x5k2tB-mo-NLiU1mLetazvpS-lJgP5is)

@AayushChaudhary0001  I looked into your comment, and here is what I found:

- We want to support spaces in the meeting topic, so we are allowing multiple arguments. Another approach could be to take a single argument after the command, which can be the meeting topic enclosed in double quotes.
- I tested the length limit of the topic on the MS Teams meeting side and found that there is no restriction on the meeting topic length from their side, so we are also not imposing any limitation on the topic's length.

2024-08-16 11:28 UTC, merged